### ISSUE TITLE
How to add a package which is not in the PureScript registry? (namely, `purescript-ocelot`)

### ISSUE THREAD

**Issue by mputz86** [purifix/purifix#57]
I am trying to add [`purescript-ocelot`](https://github.com/citizennet/purescript-ocelot/) to my purifix project, but fail to do so.

`purescript-ocelot` is not in the PureScript registry, so I thought to add it to the `extra-packages` (and `dependencies`) in the `spago.yaml` would be sufficient. But the build tries to find a `spago.yaml` for the `purescript-ocelot` repo.

```bash
...
error: getting status of '/nix/store/6wm4yjxd0c6v2687xqmrf0s8fsc8w6f9-7q8dbcr1v513m3zs0h015cwb25xh6rna-source/spago.yaml': No such file or directory
```

(this source folder is the `purescript-ocelot` repo checkout)

Can I somehow tell `purifix` to compile the `purescript-ocelot` like the packages in the PureScript registry? (assuming most/all projects on the PureScript registry have a `spago.dhall` :D)

Here is a simple, failing, `spago.yaml`, I can provide all if this is a non-trivial quetsion :D:

```yaml
package:
  name: my-package
  version: 0.0.1
  dependencies:
    [ "console"
    , "effect"
    , "foldable-traversable"
    , "halogen"
    , "ocelot"
    , "prelude"
    ]
workspace:
  package_set:
    registry: 11.3.0
  extra_packages:
    ocelot:
      git: https://github.com/citizennet/purescript-ocelot
      ref: f643e660aecab8faf71697262eb56250d058630e
```

Thanks a lot in advance :)!
